### ISSUE TITLE
Example does not work anymore locally opened unter Firefox 68.0 (64-bit)

### ISSUE THREAD

**Issue by Bozle** [mdn/simple-web-worker#18]
It seems to me, as if the example does not work anymore, if I open the file locally with Firefox 68.0 (64-bit). It works if I open the example online. Did I miss something (security options, sop)?

**Comment by chrisdavidmills** [comment]
You are right; thanks for reporting this (this also looks to be the case in latest Chrome). I'll enquire about the exact nature of this change with the engineers, and get it documented.
