### ISSUE TITLE
[Question] What is happening with this line of code?

### ISSUE THREAD

**Issue by s-truax** [mdn/simple-web-worker#25]
[Line 6](https://github.com/mdn/simple-web-worker/blob/bf6c7859c30c59a76c19a471d72e487f85d8ef45/main.js#L6) of `main.js` is
```javascript
if (window.Worker) { ... }
```
What is this line doing? My best guess is that it's just checking that the `Worker` API is supported in the current browser or execution context.

**Comment by chrisdavidmills** [comment]
@s-truax yes, that is basically correct. It is basically saying "If the `window.Worker` object exists (if the test returns `true`), then run the code inside the block."
