### ISSUE TITLE
onchange behaving like onclick and onenter, not onchange.

### ISSUE THREAD

**Issue by dschalk** [mdn/simple-web-worker#5]
Is there a way to make number changes immediately send messages to the worker. "onchange" makes it seem like this is intended, but I don't get results until I mouse click or press Enter.

**Comment by chrisdavidmills** [comment]
Hi there!

I'm sorry for taking so long to respond to this. onkeypress/down/up would work here - I prefer onkeyup, as it means that the event fires once a key has stopped being pressed, therefore the value is committed to being entered.

I am happy with the behaviour of my code, but I've added a comment to it that mentions onkeyup being a good solution if you want the behaviour you are after, as it is a useful alternative:

https://github.com/mdn/simple-web-worker/blob/gh-pages/main.js#L10-L11

thanks for bringing this up!
